export const CREATE_FIELD = 'ENTITIES/TABLES/CREATE_FIELD';
export const DELETE_FIELD = 'ENTITIES/TABLES/DELETE_FIELD';

export const CREATE_INDEX = 'ENTITIES/TABLES/CREATE_INDEX';
export const DELETE_INDEX = 'ENTITIES/TABLES/DELETE_INDEX';

export const CREATE_TRIGGER = 'ENTITIES/TABLES/CREATE_TRIGGER';
export const DELETE_TRIGGER = 'ENTITIES/TABLES/DELETE_TRIGGER';

export const CREATE_TABLE = 'ENTITIES/TABLES/CREATE_TABLE';
export const DELETE_TABLE = 'ENTITIES/TABLES/DELETE_TABLE';
export const UPDATE_TABLE = 'ENTITIES/TABLES/UPDATE_TABLE';
