export const ADD_FIELD = 'ENTITIES/TABLES/ADD_FIELD';
export const ADD_INDEX = 'ENTITIES/TABLES/ADD_INDEX';
export const ADD_TRIGGER = 'ENTITIES/TABLES/ADD_TRIGGER';

export const CREATE_TABLE = 'ENTITIES/TABLES/CREATE_TABLE';
export const DELETE_TABLE = 'ENTITIES/TABLES/DELETE_TABLE';
export const UPDATE_TABLE = 'ENTITIES/TABLES/UPDATE_TABLE';
