export const CREATE_TABLESPACE = 'VIEWS/DASHBOARD/CREATE_TABLESPACE';
export const TABLESPACE_FORM_ID = 'TABLESPACE_FORM';

export const DELETE_TABLESPACE_REQUEST = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_REQUEST';
export const DELETE_TABLESPACE_SUCCESS = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_SUCCESS';
export const DELETE_TABLESPACE_FAILURE = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_FAILURE';

export const FETCH_TABLESPACE_REQUEST = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_REQUEST';
export const FETCH_TABLESPACE_SUCCESS = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_SUCCESS';
export const FETCH_TABLESPACE_FAILURE = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_FAILURE';

export const FETCH_TABLESPACES_REQUEST = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_REQUEST';
export const FETCH_TABLESPACES_SUCCESS = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_SUCCESS';
export const FETCH_TABLESPACES_FAILURE = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_FAILURE';

export const SEND_TABLESPACE_FORM_REQUEST = 'VIEWS/DASHBOARD/SEND_TABLESPACE_FORM_REQUEST';
export const SEND_TABLESPACE_FORM_SUCCESS = 'VIEWS/DASHBOARD/SEND_TABLESPACE_FORM_SUCCESS';
export const SEND_TABLESPACE_FORM_FAILURE = 'VIEWS/DASHBOARD/SEND_TABLESPACE_FORM_FAILURE';

export const UPDATE_TABLESPACES = 'VIEWS/DASHBOARD/UPDATE_TABLESPACES';
