export const CREATE_TABLESPACE = 'VIEWS/DASHBOARD/CREATE_TABLESPACE';
export const DELETE_TABLESPACE = 'VIEWS/DASHBOARD/DELETE_TABLESPACE';
export const UPDATE_TABLESPACES = 'VIEWS/DASHBOARD/UPDATE_TABLESPACES';

export const CREATE_TABLESPACE_REQUEST = 'VIEWS/DASHBOARD/CREATE_TABLESPACE_REQUEST';
export const CREATE_TABLESPACE_SUCCESS = 'VIEWS/DASHBOARD/CREATE_TABLESPACE_SUCCESS';
export const CREATE_TABLESPACE_FAILURE = 'VIEWS/DASHBOARD/CREATE_TABLESPACE_FAILURE';

export const DELETE_TABLESPACE_REQUEST = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_REQUEST';
export const DELETE_TABLESPACE_SUCCESS = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_SUCCESS';
export const DELETE_TABLESPACE_FAILURE = 'VIEWS/DASHBOARD/DELETE_TABLESPACE_FAILURE';

export const FETCH_TABLESPACE_REQUEST = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_REQUEST';
export const FETCH_TABLESPACE_SUCCESS = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_SUCCESS';
export const FETCH_TABLESPACE_FAILURE = 'VIEWS/DASHBOARD/FETCH_TABLESPACE_FAILURE';

export const FETCH_TABLESPACES_REQUEST = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_REQUEST';
export const FETCH_TABLESPACES_SUCCESS = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_SUCCESS';
export const FETCH_TABLESPACES_FAILURE = 'VIEWS/DASHBOARD/FETCH_TABLESPACES_FAILURE';

export const TABLESPACE_FORM_ID = 'TABLESPACE_FORM';
