export const FETCH_INDEX_REQUEST = 'VIEWS/INDEXES/FETCH_INDEX_REQUEST';
export const FETCH_INDEX_SUCCESS = 'VIEWS/INDEXES/FETCH_INDEX_SUCCESS';
export const FETCH_INDEX_FAILURE = 'VIEWS/INDEXES/FETCH_INDEX_FAILURE';
