export const DELETE_INDEX_REQUEST = 'VIEWS/INDEXES/DELETE_INDEX_REQUEST';
export const DELETE_INDEX_SUCCESS = 'VIEWS/INDEXES/DELETE_INDEX_SUCCESS';
export const DELETE_INDEX_FAILURE = 'VIEWS/INDEXES/DELETE_INDEX_FAILURE';

export const FETCH_INDEX_REQUEST = 'VIEWS/INDEXES/FETCH_INDEX_REQUEST';
export const FETCH_INDEX_SUCCESS = 'VIEWS/INDEXES/FETCH_INDEX_SUCCESS';
export const FETCH_INDEX_FAILURE = 'VIEWS/INDEXES/FETCH_INDEX_FAILURE';

export const INDEXES_FORM_ID = 'indexesForm';
