export const FETCH_FIELD_REQUEST = 'VIEWS/FIELDS/FETCH_FIELD_REQUEST';
export const FETCH_FIELD_SUCCESS = 'VIEWS/FIELDS/FETCH_FIELD_SUCCESS';
export const FETCH_FIELD_FAILURE = 'VIEWS/FIELDS/FETCH_FIELD_FAILURE';
