export const CREATE_FIELD_REQUEST = 'VIEWS/FIELDS/CREATE_FIELD_REQUEST';
export const CREATE_FIELD_SUCCESS = 'VIEWS/FIELDS/CREATE_FIELD_SUCCESS';
export const CREATE_FIELD_FAILURE = 'VIEWS/FIELDS/CREATE_FIELD_FAILURE';

export const DELETE_FIELD_REQUEST = 'VIEWS/FIELDS/DELETE_FIELD_REQUEST';
export const DELETE_FIELD_SUCCESS = 'VIEWS/FIELDS/DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAILURE = 'VIEWS/FIELDS/DELETE_FIELD_FAILURE';

export const FETCH_FIELD_REQUEST = 'VIEWS/FIELDS/FETCH_FIELD_REQUEST';
export const FETCH_FIELD_SUCCESS = 'VIEWS/FIELDS/FETCH_FIELD_SUCCESS';
export const FETCH_FIELD_FAILURE = 'VIEWS/FIELDS/FETCH_FIELD_FAILURE';

export const FIELD_FORM_ID = 'fieldForm';
