export const DELETE_FIELD_REQUEST = 'VIEWS/FIELDS/DELETE_FIELD_REQUEST';
export const DELETE_FIELD_SUCCESS = 'VIEWS/FIELDS/DELETE_FIELD_SUCCESS';
export const DELETE_FIELD_FAILURE = 'VIEWS/FIELDS/DELETE_FIELD_FAILURE';

export const FETCH_FIELD_REQUEST = 'VIEWS/FIELDS/FETCH_FIELD_REQUEST';
export const FETCH_FIELD_SUCCESS = 'VIEWS/FIELDS/FETCH_FIELD_SUCCESS';
export const FETCH_FIELD_FAILURE = 'VIEWS/FIELDS/FETCH_FIELD_FAILURE';

export const SEND_FIELD_FORM_REQUEST = 'VIEWS/FIELDS/SEND_FIELD_FORM_REQUEST';
export const SEND_FIELD_FORM_SUCCESS = 'VIEWS/FIELDS/SEND_FIELD_FORM_SUCCESS';
export const SEND_FIELD_FORM_FAILURE = 'VIEWS/FIELDS/SEND_FIELD_FORM_FAILURE';

export const FIELD_FORM_ID = 'fieldForm';
