export const CREATE_TABLE = 'ENTITIES/TABLESPACES/CREATE_TABLE';
export const DELETE_TABLE = 'ENTITIES/TABLESPACES/DELETE_TABLE';

export const CREATE_TABLESPACE = 'ENTITIES/TABLESPACES/CREATE_TABLESPACE';
export const DELETE_TABLESPACE = 'ENTITIES/TABLESPACES/DELETE_TABLESPACE';
export const UPDATE_TABLESPACE = 'ENTITIES/TABLESPACES/UPDATE_TABLESPACE';
