export const CREATE_TABLE = 'VIEWS/TABLESPACE/CREATE_TABLE';
export const TABLE_FORM_ID = 'VIEWS/TABLESPACE/TABLE_FORM';

export const FETCH_TABLE_REQUEST = 'VIEWS/TABLESPACE/FETCH_TABLE_REQUEST';
export const FETCH_TABLE_SUCCESS = 'VIEWS/TABLESPACE/FETCH_TABLE_SUCCESS';
export const FETCH_TABLE_FAILURE = 'VIEWS/TABLESPACE/FETCH_TABLE_FAILURE';
