export const TABLE_FORM_ID = 'tableForm';

export const CREATE_TABLE_REQUEST = 'VIEWS/TABLESPACE/CREATE_TABLE_REQUEST';
export const CREATE_TABLE_SUCCESS = 'VIEWS/TABLESPACE/CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'VIEWS/TABLESPACE/CREATE_TABLE_FAILURE';

export const FETCH_TABLE_REQUEST = 'VIEWS/TABLESPACE/FETCH_TABLE_REQUEST';
export const FETCH_TABLE_SUCCESS = 'VIEWS/TABLESPACE/FETCH_TABLE_SUCCESS';
export const FETCH_TABLE_FAILURE = 'VIEWS/TABLESPACE/FETCH_TABLE_FAILURE';
