export const TABLE_FORM_ID = 'tableForm';
export const TABLE_DISTRIBUTE_FORM_ID = 'tableDistributeForm';

export const CREATE_TABLE_REQUEST = 'VIEWS/TABLESPACE/CREATE_TABLE_REQUEST';
export const CREATE_TABLE_SUCCESS = 'VIEWS/TABLESPACE/CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'VIEWS/TABLESPACE/CREATE_TABLE_FAILURE';

export const DELETE_TABLE_REQUEST = 'VIEWS/TABLESPACE/DELETE_TABLE_REQUEST';
export const DELETE_TABLE_SUCCESS = 'VIEWS/TABLESPACE/DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_FAILURE = 'VIEWS/TABLESPACE/DELETE_TABLE_FAILURE';

export const DISTRIBUTE_TABLE_REQUEST = 'VIEWS/TABLESPACE/DISTRIBUTE_TABLE_REQUEST';
export const DISTRIBUTE_TABLE_SUCCESS = 'VIEWS/TABLESPACE/DISTRIBUTE_TABLE_SUCCESS';
export const DISTRIBUTE_TABLE_FAILURE = 'VIEWS/TABLESPACE/DISTRIBUTE_TABLE_FAILURE';


export const FETCH_TABLE_REQUEST = 'VIEWS/TABLESPACE/FETCH_TABLE_REQUEST';
export const FETCH_TABLE_SUCCESS = 'VIEWS/TABLESPACE/FETCH_TABLE_SUCCESS';
export const FETCH_TABLE_FAILURE = 'VIEWS/TABLESPACE/FETCH_TABLE_FAILURE';
