export const CREATE_TRANSACTION = 'ENTITIES/TRANSACTIONS/CREATE_TRANSACTION';
export const DELETE_TRANSACTION = 'ENTITIES/TRANSACTIONS/DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'ENTITIES/TRANSACTIONS/UPDATE_TRANSACTION';

/** Statuses **/
export const CONFIRMATION = 'CONFIRMATION';
export const ERROR = 'ERROR';
export const PENDING = 'PENDING';
export const SUCCESS = 'SUCCESS';
