export const FETCH_TRIGGER_REQUEST = 'VIEWS/TRIGGERS/FETCH_TRIGGER_REQUEST';
export const FETCH_TRIGGER_SUCCESS = 'VIEWS/TRIGGERS/FETCH_TRIGGER_SUCCESS';
export const FETCH_TRIGGER_FAILURE = 'VIEWS/TRIGGERS/FETCH_TRIGGER_FAILURE';
