export const CREATE_TRIGGER_REQUEST = 'VIEWS/TRIGGERS/CREATE_TRIGGER_REQUEST';
export const CREATE_TRIGGER_SUCCESS = 'VIEWS/TRIGGERS/CREATE_TRIGGER_SUCCESS';
export const CREATE_TRIGGER_FAILURE = 'VIEWS/TRIGGERS/CREATE_TRIGGER_FAILURE';

export const DELETE_TRIGGER_REQUEST = 'VIEWS/TRIGGERS/DELETE_TRIGGER_REQUEST';
export const DELETE_TRIGGER_SUCCESS = 'VIEWS/TRIGGERS/DELETE_TRIGGER_SUCCESS';
export const DELETE_TRIGGER_FAILURE = 'VIEWS/TRIGGERS/DELETE_TRIGGER_FAILURE';

export const FETCH_TRIGGER_REQUEST = 'VIEWS/TRIGGERS/FETCH_TRIGGER_REQUEST';
export const FETCH_TRIGGER_SUCCESS = 'VIEWS/TRIGGERS/FETCH_TRIGGER_SUCCESS';
export const FETCH_TRIGGER_FAILURE = 'VIEWS/TRIGGERS/FETCH_TRIGGER_FAILURE';


export const TRIGGER_FORM_ID = 'triggerForm';
