export const FETCH_TRIGGER_REQUEST = 'VIEWS/TRIGGERS/FETCH_TRIGGER_REQUEST';
export const FETCH_TRIGGER_SUCCESS = 'VIEWS/TRIGGERS/FETCH_TRIGGER_SUCCESS';
export const FETCH_TRIGGER_FAILURE = 'VIEWS/TRIGGERS/FETCH_TRIGGER_FAILURE';

export const SEND_TRIGGER_FORM_REQUEST = 'VIEWS/TRIGGERS/SEND_TRIGGER_FORM_REQUEST';
export const SEND_TRIGGER_FORM_SUCCESS = 'VIEWS/TRIGGERS/SEND_TRIGGER_FORM_SUCCESS';
export const SEND_TRIGGER_FORM_FAILURE = 'VIEWS/TRIGGERS/SEND_TRIGGER_FORM_FAILURE';

export const TRIGGER_FORM_ID = 'triggerForm';
