export const FIELD_FORM_ID = 'fieldForm';
export const INDEX_FORM_ID = 'indexForm';
export const TRIGGER_FORM_ID = 'triggerForm';

export const FETCH_FIELD_REQUEST = 'VIEWS/TABLE/FETCH_FIELD_REQUEST';
export const FETCH_FIELD_SUCCESS = 'VIEWS/TABLE/FETCH_FIELD_SUCCESS';
export const FETCH_FIELD_FAILURE = 'VIEWS/TABLE/FETCH_FIELD_FAILURE';

export const FETCH_INDEX_REQUEST = 'VIEWS/TABLE/FETCH_INDEX_REQUEST';
export const FETCH_INDEX_SUCCESS = 'VIEWS/TABLE/FETCH_INDEX_SUCCESS';
export const FETCH_INDEX_FAILURE = 'VIEWS/TABLE/FETCH_INDEX_FAILURE';

export const FETCH_TRIGGER_REQUEST = 'VIEWS/TABLE/FETCH_TRIGGER_REQUEST';
export const FETCH_TRIGGER_SUCCESS = 'VIEWS/TABLE/FETCH_TRIGGER_SUCCESS';
export const FETCH_TRIGGER_FAILURE = 'VIEWS/TABLE/FETCH_TRIGGER_FAILURE';

