export const CREATE_TRANSACTION = 'SERVICES/TRANSACTIONS/CREATE_TRANSACTION';
export const DELETE_TRANSACTION = 'SERVICES/TRANSACTIONS/DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'SERVICES/TRANSACTIONS/UPDATE_TRANSACTION';
